# Generated by Django 5.1 on 2024-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('dop', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=150)),
            ],
        ),
    ]
