# Generated by Django 5.1 on 2024-08-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=20)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.manufacturer')),
            ],
        ),
    ]
