# Generated by Django 5.1 on 2024-08-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tweeter',
        ),
    ]
