# Generated by Django 5.1 on 2024-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_tweeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('dop', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='media')),
                ('caption', models.CharField(max_length=150)),
            ],
        ),
    ]
